### ISSUE TITLE
Oidc 

### ISSUE THREAD

**Issue by gedw99** [Darkness4/auth-htmx#1]
https://github.com/zitadel/zitadel-go/issues/236

I suggested your repo as a basis / example.

Maybe you also interested in a generic oidc / oath system based on htmx.

Zitadel also supports passkeys and other fancy stuff

**Comment by Darkness4** [comment]
I'm familiar with OIDC, especially since I use one (Keycloak) in my company, but I'm a bit rusty. It seems that zitadel is something similar.

As I understand it, OIDC is an identity provider with OAuth2 capability. I can use the OAuth2 flow easily by parsing the discovery document ([google example](https://accounts.google.com/.well-known/openid-configuration), and instead of calling the Github API to verify and retrieve user information, I can use the [ID token](https://developers.google.com/identity/openid-connect/openid-connect#exchangecode), [validate it by verifying a signature and certificates](https://developers.google.com/identity/openid-connect/openid-connect#validatinganidtoken) and [retrieve user information using the OIDC-compliant `scope`](https://developers.google.com/identity/openid-connect/openid-connect#obtaininguserprofileinformation). 

While it seems interesting to extend the experiment to OIDC, it's a shame that Github doesn't support OIDC. I may extend the example with Google Auth, through.

Theorically, it looks like I must:

1. Change the `scope` of the login function and add `openid profile email`.
2. Remove any hard-coded value about authorizationURL, userURL etc... and use the discovery document.
3. Parse and verify the ID token in my `getCurrentUser` instead of calling the Github API.

To be fair, I should use the [go-oidc](https://github.com/coreos/go-oidc) package instead. And I should have used the package [oauth2](https://pkg.go.dev/golang.org/x/oauth2). Right now, the implementation is very "naive".

**Comment by Darkness4** [comment]
Support added with `go-oidc` and `oauth2`: https://github.com/Darkness4/auth-htmx/commit/829a866a36aab9f499fd613bf8118fb92da5eab1
